sudo: required
language: generic

services: 
  - docker

before_install:
  - docker build -t wartynas/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true wartynas/docker-react npm run test