sudo: required # we tell travis that we need sudo level persmissions to execute this build
language: generic

services: 
  - docker # step 1

# a series of commands that are executed before the tests are run
before_install:
  - docker build -t wartynas/docker-react -f Dockerfile.dev . # step 2

# this section contains a list of commands that need to be executed in order to run tests
script:
  - docker run -e CI=true wartynas/docker-react npm run test # step 3