sudo: required
language: generic

services: 
  - docker

before_install:
  - docker build -t wartynas/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true wartynas/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1" # this was extracted from the URL link
  name: "docker-react"
  env: "Dockerreact-env"
  bucket-name: "elasticbeanstalk-us-east-1-775075961641"
  bucket-path: "docker-react"
  on:
    branch: master # any time code in master changes, it's time to deploy
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY" 