version: '3'
services:
  react-app:
    build:
      context: . # where are all the files located for this project
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules # do not try to map node_modules directory to anything
      - .:/app # map current directory from outside the container to the /app folder inside the container
  tests:
    build:
      context: . # where are all the files located for this project
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules # do not try to map node_modules directory to anything
      - .:/app
    command: ["npm", "run", "test"]