# need to use specific version to avoid errors
FROM node:16-alpine

# set up a working directory
WORKDIR '/app' 

# copy package.json to /app
COPY package.json . 

# install dependencies
RUN npm install

# added this line because I was getting error: https://stackoverflow.com/questions/67087735/eacces-permission-denied-mkdir-usr-app-node-modules-cache-how-can-i-creat
RUN mkdir -p node_modules/.cache && chmod -R 777 node_modules/.cache

# copy the rest of the files to /app
COPY . .

CMD ["npm", "run", "start"]